### ISSUE TITLE
Replacement for 2N2007E MOSFET

### ISSUE THREAD

**Issue by ethicstechOSS** [StudioSophisti/ESP-WROOM-32-Eagle-Breakout#2]
Hi. I am unable to find stock availability of this component, 2N2007E mosfet from Farnell (Part #1894721) as well as from DigiKey. Can you suggest any replacement for this component?.

TIA,
Prakash.

**Comment by tijnkooijmans** [comment]
Hi Prakash, 

Thanks for noticing, indeed NXP stopt producing it but there are plenty of others. Please use this one instead: Farnell 2317616

I will update the documentation.

Best regards,
Tijn
